Update story
imadahirosi/momotaro pull request #1
Opened 2021-06-21 11:48 UTC by tomato3713

2021-06-23 15:35 UTC, imadahirosi requested changes
thank you for your pull request.
some code is not "readable English"

2021-06-23 15:35 UTC, imadahirosi commented on momotaro.c
> +  a momo = flow("kawa");
a peach flows through the river

2021-06-23 15:35 UTC, imadahirosi commented on momotaro.c
> +  an momotaro = cut(momo);
a baby come out from peach
baby was named "momotaro"

2021-06-23 15:46 UTC, imadahirosi requested changes
update your fork.
now, parent repository source code has discription comment.
insert your name to "Authors" in discription.

2021-06-23 15:46 UTC, imadahirosi commented on momotaro.c
>  #include<stdio.h>
update your fork.
now, parent repository source code has discription comment.
insert your name to "Authors" in discription.

2021-06-25 01:08 UTC, tomato3713 commented
Thanks for your reviews. 
I fixed not "readable english" code. and add my name to "Authors".

2021-07-19 03:07 UTC, tomato3713 commented
I deleted the a.exe.

2021-08-07 15:01 UTC, merged